export interface DriftRecord {
  id: string;
  resourceId: string;
  subsystem: string;
  port: string;
  expectedState: string;
  actualState: string;
  driftType: "Orphan" | "Mismatch" | "Missing";
  linkedOrder: string;
  remediationAction: string;
  remediationStatus: "success" | "warning";
  timestamp: string;
  diffDetails: {
    msisdn?: string;
    imsi?: string;
    subsystemNode?: string;
    hypothesis: string;
    actualLines: string[];
    expectedLines: string[];
    traces: Array<{ time: string; text: string; status: "normal" | "error" | "info" | "success" }>;
  };
}

export interface SweepIntervalDataset {
  interval: "1m" | "5m" | "15m" | "1h";
  lastSweep: string;
  elapsedAgo: string;
  nextAuditIn: string;
  epoch: number;
  scannedResources: string;
  driftCount: number;
  driftRate: string;
  autoRepaired: number;
  autoRepairedRate: string;
  escalatedToFallout: number;
  subsystemCount: number;
  consensusTarget: string;
  records: DriftRecord[];
}

export const SWEEP_DATASETS: Record<"1m" | "5m" | "15m" | "1h", SweepIntervalDataset> = {
  "1m": {
    interval: "1m",
    lastSweep: "2026-07-12 14:31:02 UTC",
    elapsedAgo: "22s ago",
    nextAuditIn: "in 38s",
    epoch: 8945,
    scannedResources: "2,840",
    driftCount: 2,
    driftRate: "0.070%",
    autoRepaired: 2,
    autoRepairedRate: "100%",
    escalatedToFallout: 0,
    subsystemCount: 4,
    consensusTarget: "100.0%",
    records: [
      {
        id: "drift-1m-1",
        resourceId: "hlr-sub-transient-fast-019",
        subsystem: "HLR/HSS Gateway",
        port: ":8443",
        expectedState: "DECOMMISSIONED_TOMBSTONE",
        actualState: "ACTIVE (Transient unpurged)",
        driftType: "Orphan",
        linkedOrder: "ORD-20260712-004221",
        remediationAction: "Fast Lock Purge #91",
        remediationStatus: "success",
        timestamp: "14:31:01 UTC",
        diffDetails: {
          subsystemNode: "us-east-hlr-node-01",
          msisdn: "+91 98201 14002",
          imsi: "404450192837401",
          hypothesis: "Sub-second HSS slice deregistration packet delayed during burst failover",
          actualLines: [
            'status: "PROVISIONED_ACTIVE"',
            'slice_qos: "5QI-9_250M"',
            "locked: false",
            'active_tunnels: [ "tun_hlr_101" ]',
          ],
          expectedLines: [
            'status: "DECOMMISSIONED_TOMBSTONE"',
            "slice_qos: null",
            "locked: true",
            "active_tunnels: []",
          ],
          traces: [
            { time: "14:31:01.102", text: "Fast 1-minute poller queried HLR slice 01", status: "normal" },
            { time: "14:31:01.314", text: "Transient orphan slice detected", status: "error" },
            { time: "14:31:01.520", text: "Dispatched Fast Lock Purge #91", status: "info" },
            { time: "14:31:01.780", text: "Subsystem tombstone verified: 200 OK", status: "success" },
          ],
        },
      },
      {
        id: "drift-1m-2",
        resourceId: "sim-lease-quick-88102",
        subsystem: "SIM Inventory",
        port: ":9001",
        expectedState: "RESERVED (IMSI 404450918)",
        actualState: "UNALLOCATED (Optimistic unlock)",
        driftType: "Mismatch",
        linkedOrder: "ORD-20260712-004219",
        remediationAction: "Auto-Relock #114",
        remediationStatus: "success",
        timestamp: "14:30:58 UTC",
        diffDetails: {
          subsystemNode: "us-east-sim-db-03",
          msisdn: "+91 98450 28190",
          imsi: "404450918204911",
          hypothesis: "Concurrent catalog reservation released ephemeral lock",
          actualLines: ['lock_state: "UNLOCKED"', 'allocated_to: null'],
          expectedLines: ['lock_state: "LOCKED_RESERVED"', 'allocated_to: "ORD-20260712-004219"'],
          traces: [
            { time: "14:30:58.201", text: "Queried SIM pool active partition", status: "normal" },
            { time: "14:30:58.411", text: "Lock mismatch detected", status: "error" },
            { time: "14:30:58.622", text: "Applied Auto-Relock #114 with 60s lease", status: "info" },
            { time: "14:30:58.905", text: "Reservation lock restored and committed", status: "success" },
          ],
        },
      },
    ],
  },

  "5m": {
    interval: "5m",
    lastSweep: "2026-07-12 14:28:45 UTC",
    elapsedAgo: "2m 14s ago",
    nextAuditIn: "in 2m 46s",
    epoch: 8941,
    scannedResources: "14,280",
    driftCount: 7,
    driftRate: "0.049%",
    autoRepaired: 5,
    autoRepairedRate: "71.4%",
    escalatedToFallout: 2,
    subsystemCount: 4,
    consensusTarget: "100.0%",
    records: [
      {
        id: "drift-1",
        resourceId: "hlr-profile-500mbps-9182",
        subsystem: "HLR/HSS Gateway",
        port: ":8443",
        expectedState: "TERMINATED / DEPROVISIONED",
        actualState: "ACTIVE (Leaked HLR slice)",
        driftType: "Orphan",
        linkedOrder: "ORD-20260712-004217",
        remediationAction: "Inverse Saga #419",
        remediationStatus: "success",
        timestamp: "14:28:43 UTC",
        diffDetails: {
          subsystemNode: "us-east-hlr-node-04b",
          msisdn: "+14155552671",
          imsi: "310410091824701",
          hypothesis: "HLR deprovision gRPC call timed out at stage 4 of saga compensation",
          actualLines: [
            'status: "PROVISIONED_ACTIVE"',
            'slice_qos: "5QI-9_500M"',
            "locked: false",
            'active_tunnels: [ "tun_hlr_880", "tun_hlr_881" ]',
          ],
          expectedLines: [
            'status: "DECOMMISSIONED_TOMBSTONE"',
            "slice_qos: null",
            "locked: true",
            "active_tunnels: []",
            'deprovision_tx_hash: "0x7c9be309f44ea1d9"',
          ],
          traces: [
            { time: "14:28:43.012", text: "Subsystem state polled via HLR Gateway gRPC", status: "normal" },
            { time: "14:28:43.418", text: "Drift identified: Subsystem ACTIVE, OMS intent TERMINATED", status: "error" },
            { time: "14:28:43.890", text: "Invoked Compensating Saga #419 with Safe Invariant Guard", status: "info" },
            { time: "14:28:44.215", text: "HLR profile deprovision confirmed: ACK 200 OK", status: "success" },
          ],
        },
      },
      {
        id: "drift-2",
        resourceId: "sim-iccid-8901410321",
        subsystem: "SIM Inventory",
        port: ":9001",
        expectedState: "RESERVED (IMSI 310410091)",
        actualState: "UNALLOCATED (Missing lock)",
        driftType: "Mismatch",
        linkedOrder: "ORD-20260712-004212",
        remediationAction: "Saga Re-lock #420",
        remediationStatus: "success",
        timestamp: "14:28:39 UTC",
        diffDetails: {
          subsystemNode: "us-east-sim-db-01",
          msisdn: "+14155552199",
          imsi: "310410091",
          hypothesis: "Transient DB deadlock released optimistic lock during concurrent batch update",
          actualLines: ['lock_state: "UNLOCKED"', 'allocated_to: null', "reservation_lease: 0"],
          expectedLines: [
            'lock_state: "LOCKED_RESERVED"',
            'allocated_to: "ORD-20260712-004212"',
            "reservation_lease: 3600",
            'lease_signature: "0xa841b9c2"',
          ],
          traces: [
            { time: "14:28:39.102", text: "Polled SIM registry partition key 890141", status: "normal" },
            { time: "14:28:39.314", text: "Drift identified: Lock released prematurely", status: "error" },
            { time: "14:28:39.521", text: "Acquiring idempotent lock lease with 1hr TTL", status: "info" },
            { time: "14:28:39.802", text: "SIM lock restored and confirmed in SIM pool", status: "success" },
          ],
        },
      },
      {
        id: "drift-3",
        resourceId: "ocs-balance-acct-88201",
        subsystem: "OCS Billing",
        port: ":8082",
        expectedState: "PLAN: Fiber_500 (ACTIVE)",
        actualState: "SUSPENDED (Billing mismatch)",
        driftType: "Mismatch",
        linkedOrder: "ORD-20260712-003980",
        remediationAction: "Fallout #FL-1092",
        remediationStatus: "warning",
        timestamp: "14:28:31 UTC",
        diffDetails: {
          subsystemNode: "us-east-ocs-cluster-02",
          msisdn: "+14155558820",
          hypothesis: "Credit check hold conflict triggered circuit breaker, preventing auto-resume",
          actualLines: ['tariff_status: "SUSPENDED"', "quota_balance_mb: 0", 'lock_cause: "CREDIT_COLLISION_409"'],
          expectedLines: ['tariff_status: "ACTIVE"', "quota_balance_mb: 512000", 'plan_code: "FIBER_500_UNLIMITED"'],
          traces: [
            { time: "14:28:31.004", text: "Polled OCS Diameter credit control interface", status: "normal" },
            { time: "14:28:31.250", text: "State divergence: Expected ACTIVE, found SUSPENDED", status: "error" },
            { time: "14:28:31.600", text: "Safety invariant circuit breaker triggered (Manual review required)", status: "error" },
            { time: "14:28:31.810", text: "Dispatched to Fallout Queue as FL-1092", status: "info" },
          ],
        },
      },
      {
        id: "drift-4",
        resourceId: "gis-ont-port-14/b",
        subsystem: "Physical Inventory",
        port: ":7040",
        expectedState: "LOCKED_FOR_ROLLBACK",
        actualState: "AVAILABLE (Orphaned)",
        driftType: "Orphan",
        linkedOrder: "ORD-20260712-003975",
        remediationAction: "Inverse Saga #416",
        remediationStatus: "success",
        timestamp: "14:28:22 UTC",
        diffDetails: {
          subsystemNode: "us-east-gis-splitter-14",
          hypothesis: "Field ONT assignment reverted before rollback completed in OMS",
          actualLines: ['port_state: "AVAILABLE_POOLED"', "optical_path_id: null"],
          expectedLines: ['port_state: "LOCKED_FOR_ROLLBACK"', 'optical_path_id: "OPT-PORT-14B"', 'rollback_token: "0x416-ont-drain"'],
          traces: [
            { time: "14:28:22.019", text: "Polled GIS physical fiber inventory DB", status: "normal" },
            { time: "14:28:22.311", text: "Detected orphan port release", status: "error" },
            { time: "14:28:22.618", text: "Executing Inverse Saga #416 to acquire rollback quarantine", status: "info" },
            { time: "14:28:22.990", text: "Port successfully locked for rollback completion", status: "success" },
          ],
        },
      },
      {
        id: "drift-5",
        resourceId: "oms-order-intent-4217",
        subsystem: "OMS Core",
        port: ":8080",
        expectedState: "STATUS: COMPENSATED",
        actualState: "STATUS: RUNNING (Ghost lock)",
        driftType: "Missing",
        linkedOrder: "ORD-20260712-004217",
        remediationAction: "Temporal Sync #882",
        remediationStatus: "success",
        timestamp: "14:28:18 UTC",
        diffDetails: {
          subsystemNode: "us-east-oms-kernel-01",
          hypothesis: "Temporal workflow completed compensation but worker crash delayed DB status projection",
          actualLines: ['saga_status: "RUNNING"', 'active_activities: [ "deprovision_hlr" ]', "db_version: 14"],
          expectedLines: ['saga_status: "COMPENSATED"', "active_activities: []", "db_version: 15", 'temporal_execution_status: "COMPLETED_REVERTED"'],
          traces: [
            { time: "14:28:18.110", text: "Auditing OMS local ledger vs Temporal workflow history", status: "normal" },
            { time: "14:28:18.412", text: "Discrepancy: Temporal closed but DB reports RUNNING", status: "error" },
            { time: "14:28:18.700", text: "Replaying projection stream from Temporal history", status: "info" },
            { time: "14:28:19.015", text: "State synchronized to COMPENSATED (v15)", status: "success" },
          ],
        },
      },
      {
        id: "drift-6",
        resourceId: "hlr-profile-voice-qos-904",
        subsystem: "HLR/HSS Gateway",
        port: ":8443",
        expectedState: "QOS_5QI: 1 (VoLTE priority)",
        actualState: "QOS_5QI: 9 (Default Best-Effort)",
        driftType: "Mismatch",
        linkedOrder: "ORD-20260712-003890",
        remediationAction: "Fallout #FL-1089",
        remediationStatus: "warning",
        timestamp: "14:28:11 UTC",
        diffDetails: {
          subsystemNode: "us-east-hlr-node-02a",
          msisdn: "+14155553890",
          hypothesis: "HLR fallback provisioned default QoS template after 5G QoS parameter syntax reject",
          actualLines: ["qos_5qi: 9", 'qos_label: "BEST_EFFORT_DEFAULT"', 'override_reason: "SYNTAX_PARAM_REJECT"'],
          expectedLines: ["qos_5qi: 1", 'qos_label: "MISSION_CRITICAL_VOICE"', "gbr_dl_mbps: 100"],
          traces: [
            { time: "14:28:11.002", text: "Queried HLR active slice QoS telemetry", status: "normal" },
            { time: "14:28:11.319", text: "QoS class mismatch: Expected 5QI 1, observed 5QI 9", status: "error" },
            { time: "14:28:11.644", text: "Syntax flag prevents auto-repair without plan schema patch", status: "error" },
            { time: "14:28:11.902", text: "Escalated to Fallout Queue as FL-1089", status: "info" },
          ],
        },
      },
      {
        id: "drift-7",
        resourceId: "imsi-binding-310410099",
        subsystem: "SIM Inventory",
        port: ":9001",
        expectedState: "ALLOCATED (MSISDN +14155552671)",
        actualState: "STALE_QUARANTINE",
        driftType: "Orphan",
        linkedOrder: "ORD-20260712-003844",
        remediationAction: "State Flush #384",
        remediationStatus: "success",
        timestamp: "14:28:02 UTC",
        diffDetails: {
          subsystemNode: "us-east-sim-db-02",
          msisdn: "+14155552671",
          hypothesis: "Quarantine cleanup cron missed tombstoned IMSI after rapid order swap",
          actualLines: ['status: "STALE_QUARANTINE"', 'quarantine_entered: "2026-07-12T13:40:00Z"', 'bound_msisdn: "+14155552671"'],
          expectedLines: ['status: "ALLOCATED"', "active_binding: true", "quarantine_entered: null", 'flush_digest: "0x9812af"'],
          traces: [
            { time: "14:28:02.120", text: "Scanning SIM inventory quarantine partition", status: "normal" },
            { time: "14:28:02.404", text: "Found stale quarantine entry for active subscription", status: "error" },
            { time: "14:28:02.690", text: "Flushing stale quarantine flag via State Flush #384", status: "info" },
            { time: "14:28:03.012", text: "IMSI binding cleared and verified ALLOCATED", status: "success" },
          ],
        },
      },
    ],
  },

  "15m": {
    interval: "15m",
    lastSweep: "2026-07-12 14:15:00 UTC",
    elapsedAgo: "15m 28s ago",
    nextAuditIn: "in 4m 32s",
    epoch: 8939,
    scannedResources: "42,850",
    driftCount: 14,
    driftRate: "0.032%",
    autoRepaired: 11,
    autoRepairedRate: "78.6%",
    escalatedToFallout: 3,
    subsystemCount: 4,
    consensusTarget: "100.0%",
    records: [
      {
        id: "drift-15m-1",
        resourceId: "ocs-tariff-plan-lock-1002",
        subsystem: "OCS Billing",
        port: ":8082",
        expectedState: "ACTIVE (POSTPAID_500)",
        actualState: "RATE_THROTTLED (Orphaned ceiling)",
        driftType: "Mismatch",
        linkedOrder: "ORD-20260712-003612",
        remediationAction: "Ceiling Reset #712",
        remediationStatus: "success",
        timestamp: "14:14:52 UTC",
        diffDetails: {
          subsystemNode: "us-east-ocs-node-03",
          msisdn: "+91 99820 18234",
          hypothesis: "Previous billing cycle reconciliation left stale QoS throttle bucket",
          actualLines: ['bucket_state: "THROTTLED"', "max_dl_kbps: 64", 'throttle_flag: true'],
          expectedLines: ['bucket_state: "STANDARD"', "max_dl_kbps: 512000", 'throttle_flag: false'],
          traces: [
            { time: "14:14:52.010", text: "15m batch reconciler polled OCS rating rules", status: "normal" },
            { time: "14:14:52.289", text: "Stale throttle ceiling divergence discovered", status: "error" },
            { time: "14:14:52.540", text: "Executed Ceiling Reset #712", status: "info" },
            { time: "14:14:52.880", text: "Full gigabit bandwidth policy restored", status: "success" },
          ],
        },
      },
      {
        id: "drift-15m-2",
        resourceId: "hlr-auth-vector-pool-441",
        subsystem: "HLR/HSS Gateway",
        port: ":8443",
        expectedState: "CONSUMED_TOMBSTONE",
        actualState: "AVAILABLE_IN_POOL (Leaked vector)",
        driftType: "Orphan",
        linkedOrder: "ORD-20260712-003598",
        remediationAction: "Vector Purge #89",
        remediationStatus: "success",
        timestamp: "14:14:40 UTC",
        diffDetails: {
          subsystemNode: "us-east-hlr-node-02b",
          msisdn: "+91 98110 44921",
          imsi: "404450882104992",
          hypothesis: "AKA crypto challenge vector was not consumed following failed activation retry",
          actualLines: ['vector_status: "AVAILABLE"', "challenge_seq: 14"],
          expectedLines: ['vector_status: "CONSUMED_TOMBSTONE"', "challenge_seq: 15"],
          traces: [
            { time: "14:14:40.118", text: "Auditing auth vector consistency across HLR slices", status: "normal" },
            { time: "14:14:40.401", text: "Vector leak found for completed order", status: "error" },
            { time: "14:14:40.710", text: "Tombstoning challenge key via Vector Purge #89", status: "info" },
            { time: "14:14:40.994", text: "Crypto vector cleanly invalidated", status: "success" },
          ],
        },
      },
      {
        id: "drift-15m-3",
        resourceId: "sim-esim-eid-8904901928",
        subsystem: "SIM Inventory",
        port: ":9001",
        expectedState: "DOWNLOAD_CONFIRMED",
        actualState: "PENDING_SMDP (Profile held)",
        driftType: "Missing",
        linkedOrder: "ORD-20260712-003550",
        remediationAction: "SM-DP+ Sync #301",
        remediationStatus: "success",
        timestamp: "14:14:22 UTC",
        diffDetails: {
          subsystemNode: "us-east-smdp-relay-01",
          hypothesis: "RSP notification delayed across operator carrier gateway webhook",
          actualLines: ['profile_status: "RELEASED"', 'device_ack: false'],
          expectedLines: ['profile_status: "INSTALLED"', 'device_ack: true'],
          traces: [
            { time: "14:14:22.050", text: "Scanning eSIM RSP server transaction log", status: "normal" },
            { time: "14:14:22.312", text: "SM-DP+ status out of sync with inventory database", status: "error" },
            { time: "14:14:22.618", text: "Triggered SM-DP+ Sync #301", status: "info" },
            { time: "14:14:22.910", text: "Device profile installation receipt reconciled", status: "success" },
          ],
        },
      },
    ],
  },

  "1h": {
    interval: "1h",
    lastSweep: "2026-07-12 14:00:00 UTC",
    elapsedAgo: "30m 28s ago",
    nextAuditIn: "in 29m 32s",
    epoch: 8935,
    scannedResources: "168,400",
    driftCount: 38,
    driftRate: "0.022%",
    autoRepaired: 34,
    autoRepairedRate: "89.5%",
    escalatedToFallout: 4,
    subsystemCount: 4,
    consensusTarget: "100.0%",
    records: [
      {
        id: "drift-1h-1",
        resourceId: "hlr-bulk-tenant-slice-west-88",
        subsystem: "HLR/HSS Gateway",
        port: ":8443",
        expectedState: "DYNAMIC_SLICE_POOL (CAP: 10k)",
        actualState: "ALLOCATED_STALE (Ghost tenant)",
        driftType: "Orphan",
        linkedOrder: "ORD-20260712-002100",
        remediationAction: "Tenant Partition Purge #55",
        remediationStatus: "success",
        timestamp: "13:59:45 UTC",
        diffDetails: {
          subsystemNode: "us-west-hlr-cluster-01",
          hypothesis: "Tenant slice deallocation missed across hourly macro-sweep garbage collector",
          actualLines: ['slice_state: "BOUND_ENTERPRISE"', "active_subs_count: 0", "last_tx: 3600s_ago"],
          expectedLines: ['slice_state: "POOLED_AVAILABLE"', "active_subs_count: 0", "last_tx: null"],
          traces: [
            { time: "13:59:45.012", text: "Hourly macro sweep scanning 168k records", status: "normal" },
            { time: "13:59:45.890", text: "Dormant tenant slice discovered with zero active subscribers", status: "error" },
            { time: "13:59:46.410", text: "Running Tenant Partition Purge #55", status: "info" },
            { time: "13:59:47.100", text: "Returned 10,000 capacity back to pooled allocation", status: "success" },
          ],
        },
      },
      {
        id: "drift-1h-2",
        resourceId: "gis-optical-line-terminal-slot-08",
        subsystem: "Physical Inventory",
        port: ":7040",
        expectedState: "DECOMMISSIONED_MAINTENANCE",
        actualState: "REPORTED_UP (Firmware telemetry loop)",
        driftType: "Mismatch",
        linkedOrder: "ORD-20260712-001944",
        remediationAction: "Fallout #FL-1044",
        remediationStatus: "warning",
        timestamp: "13:59:12 UTC",
        diffDetails: {
          subsystemNode: "us-east-olt-chassis-08",
          hypothesis: "Firmware loop in OLT line card continuous heartbeat during scheduled maintenance",
          actualLines: ['chassis_card_status: "OPERATIONAL"', 'laser_power_mw: 0.0'],
          expectedLines: ['chassis_card_status: "MAINTENANCE_OFFLINE"', 'laser_power_mw: 0.0'],
          traces: [
            { time: "13:59:12.112", text: "Macro hourly SNMP physical inventory sweep", status: "normal" },
            { time: "13:59:12.550", text: "Chassis status reported OPERATIONAL despite planned maintenance", status: "error" },
            { time: "13:59:12.920", text: "Escalated to Fallout NOC queue as FL-1044", status: "info" },
          ],
        },
      },
      {
        id: "drift-1h-3",
        resourceId: "ocs-batch-ledger-reconciliation-99",
        subsystem: "OCS Billing",
        port: ":8082",
        expectedState: "SETTLED_CLOSED",
        actualState: "OPEN_UNFINALIZED",
        driftType: "Missing",
        linkedOrder: "ORD-20260712-001802",
        remediationAction: "Batch Settle #204",
        remediationStatus: "success",
        timestamp: "13:58:30 UTC",
        diffDetails: {
          subsystemNode: "us-east-ocs-settlement-01",
          hypothesis: "Hourly settlement cron delayed by high concurrent checkout volume",
          actualLines: ['settlement_batch: "OPEN"', 'unfinalized_tx_count: 12'],
          expectedLines: ['settlement_batch: "CLOSED"', 'unfinalized_tx_count: 0'],
          traces: [
            { time: "13:58:30.201", text: "Checking ledger closure status", status: "normal" },
            { time: "13:58:30.612", text: "Unfinalized transactions found in closed window", status: "error" },
            { time: "13:58:31.002", text: "Running Batch Settle #204", status: "info" },
            { time: "13:58:31.450", text: "Ledger closure sealed and synchronized", status: "success" },
          ],
        },
      },
    ],
  },
};
