/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
      "4xl": "2560px",
    },
    extend: {
      colors: {
        // DUAL TONE PALETTE: WHITE BACKGROUND & DEEP NAVY BLUE
        antigravity: {
          arctic: "#FFFFFF",
          navy: "#0A1B2E",
          slate: "#0A1B2E",
        },
        navy: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0A1B2E", // Deep Navy
          950: "#06111f",
        },
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffffff",
        "surface-container": "#ffffff",
        "surface-container-high": "#ffffff",
        "surface-container-highest": "#f8fafc",
        surface: "#ffffff",
        background: "#ffffff",
        "surface-dim": "#f8fafc",
        "surface-bright": "#ffffff",
        "surface-variant": "#ffffff",
        "inverse-surface": "#0A1B2E",
        "inverse-on-surface": "#ffffff",

        // Core Structural & Interactive: Deep Navy (#0A1B2E)
        primary: "#0A1B2E",
        "primary-container": "#14263b",
        "primary-fixed": "#f1f5f9",
        "primary-fixed-dim": "#e2e8f0",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#0A1B2E",
        "on-primary-fixed-variant": "#14263b",
        "inverse-primary": "#cbd5e1",
        "surface-tint": "#0A1B2E",

        // Secondary & Tertiary: Deep Navy & White
        secondary: "#0A1B2E",
        "secondary-container": "#14263b",
        "secondary-fixed": "#f1f5f9",
        "secondary-fixed-dim": "#e2e8f0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#ffffff",
        "on-secondary-fixed": "#0A1B2E",
        "on-secondary-fixed-variant": "#14263b",

        tertiary: "#0A1B2E",
        "tertiary-container": "#14263b",
        "tertiary-fixed": "#f1f5f9",
        "tertiary-fixed-dim": "#e2e8f0",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#0A1B2E",
        "on-tertiary-fixed-variant": "#14263b",

        // Typography & Outlines: Crisp Navy Blue & Subtle Borders
        "on-surface": "#0A1B2E",
        "on-surface-variant": "#0A1B2E",
        "on-background": "#0A1B2E",
        outline: "#CBD5E1",
        "outline-variant": "#E2E8F0",

        // Unified status tokens
        error: "#0A1B2E",
        "on-error": "#ffffff",
        "error-container": "#ffffff",
        "on-error-container": "#0A1B2E",
      },
      fontFamily: {
        "label-md": ["'JetBrains Mono'", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["'JetBrains Mono'", "monospace"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
