/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dae2fd",
        "surface-container": "#eaedff",
        "on-primary-container": "#dad7ff",
        "on-tertiary-fixed-variant": "#38485d",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed-variant": "#003ea8",
        "inverse-surface": "#283044",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed": "#0b1c30",
        "on-background": "#131b2e",
        "on-primary": "#ffffff",
        "surface-dim": "#d2d9f4",
        tertiary: "#3a495f",
        "tertiary-fixed": "#d3e4fe",
        "surface-tint": "#4d44e3",
        secondary: "#0051d5",
        primary: "#3525cd",
        "secondary-container": "#316bf3",
        "inverse-primary": "#c3c0ff",
        background: "#faf8ff",
        "primary-container": "#4f46e5",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#b7c8e1",
        outline: "#777587",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed": "#dbe1ff",
        surface: "#faf8ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00174b",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#3323cc",
        "error-container": "#ffdad6",
        "on-secondary-container": "#fefcff",
        "primary-fixed-dim": "#c3c0ff",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "on-tertiary-container": "#ccdcf7",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "tertiary-container": "#516177",
        "on-surface-variant": "#464555",
        "on-primary-fixed": "#0f0069",
      },
      fontFamily: {
        "label-md": ["'JetBrains Mono'", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["'JetBrains Mono'", "monospace"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
